# Generated by Django 3.2.6 on 2023-08-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('archivada', models.BooleanField(default=False)),
            ],
        ),
    ]
