# Generated by Django 3.2.6 on 2023-08-09 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
