# Generated by Django 3.2.6 on 2023-08-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_noticia_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
    ]
