version: "3"
services:
  web:
    hostname: web
    build:
      context: .
    expose:
      - "5000"
    volumes:
      - /home/fisa/devel/ucse/seia/data_docker/:/myweb/data/
    depends_on:
      - db
      - cache

  db:
    image: "postgres:13.0"
    volumes:
      - /home/fisa/devel/ucse/seia/data_docker_db/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=my_web
      - POSTGRES_PASSWORD=paparulo
      - POSTGRES_DB=my_web

  sessions:
    image: "memcached:1.5.5"

  load_balancer:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    ports:
      - "5000:5000"
